//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWPFClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class StudentViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class GroupViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class TestViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class QuestionViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TestId {
            get {
                return this.TestIdField;
            }
            set {
                if ((this.TestIdField.Equals(value) != true)) {
                    this.TestIdField = value;
                    this.RaisePropertyChanged("TestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class AnswerViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect {
            get {
                return this.IsCorrectField;
            }
            set {
                if ((this.IsCorrectField.Equals(value) != true)) {
                    this.IsCorrectField = value;
                    this.RaisePropertyChanged("IsCorrect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class ResultViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CorrectCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResultDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan SpentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CorrectCount {
            get {
                return this.CorrectCountField;
            }
            set {
                if ((this.CorrectCountField.Equals(value) != true)) {
                    this.CorrectCountField = value;
                    this.RaisePropertyChanged("CorrectCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResultDate {
            get {
                return this.ResultDateField;
            }
            set {
                if ((this.ResultDateField.Equals(value) != true)) {
                    this.ResultDateField = value;
                    this.RaisePropertyChanged("ResultDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan SpentTime {
            get {
                return this.SpentTimeField;
            }
            set {
                if ((this.SpentTimeField.Equals(value) != true)) {
                    this.SpentTimeField = value;
                    this.RaisePropertyChanged("SpentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestId {
            get {
                return this.TestIdField;
            }
            set {
                if ((this.TestIdField.Equals(value) != true)) {
                    this.TestIdField = value;
                    this.RaisePropertyChanged("TestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultAnswerViewModel", Namespace="http://schemas.datacontract.org/2004/07/DataViewModels")]
    [System.SerializableAttribute()]
    public partial class ResultAnswerViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerId {
            get {
                return this.AnswerIdField;
            }
            set {
                if ((this.AnswerIdField.Equals(value) != true)) {
                    this.AnswerIdField = value;
                    this.RaisePropertyChanged("AnswerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultId {
            get {
                return this.ResultIdField;
            }
            set {
                if ((this.ResultIdField.Equals(value) != true)) {
                    this.ResultIdField = value;
                    this.RaisePropertyChanged("ResultId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IStudentTestService")]
    public interface IStudentTestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetStudents", ReplyAction="http://tempuri.org/IStudentTestService/GetStudentsResponse")]
        AdminWPFClient.ServiceReference.StudentViewModel[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetStudents", ReplyAction="http://tempuri.org/IStudentTestService/GetStudentsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.StudentViewModel[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetGroups", ReplyAction="http://tempuri.org/IStudentTestService/GetGroupsResponse")]
        AdminWPFClient.ServiceReference.GroupViewModel[] GetGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetGroups", ReplyAction="http://tempuri.org/IStudentTestService/GetGroupsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.GroupViewModel[]> GetGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTests", ReplyAction="http://tempuri.org/IStudentTestService/GetTestsResponse")]
        AdminWPFClient.ServiceReference.TestViewModel[] GetTests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTests", ReplyAction="http://tempuri.org/IStudentTestService/GetTestsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.TestViewModel[]> GetTestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetStudentTests", ReplyAction="http://tempuri.org/IStudentTestService/GetStudentTestsResponse")]
        AdminWPFClient.ServiceReference.TestViewModel[] GetStudentTests(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetStudentTests", ReplyAction="http://tempuri.org/IStudentTestService/GetStudentTestsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.TestViewModel[]> GetStudentTestsAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTestQuestions", ReplyAction="http://tempuri.org/IStudentTestService/GetTestQuestionsResponse")]
        AdminWPFClient.ServiceReference.QuestionViewModel[] GetTestQuestions(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTestQuestions", ReplyAction="http://tempuri.org/IStudentTestService/GetTestQuestionsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.QuestionViewModel[]> GetTestQuestionsAsync(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetQuestionAnswers", ReplyAction="http://tempuri.org/IStudentTestService/GetQuestionAnswersResponse")]
        AdminWPFClient.ServiceReference.AnswerViewModel[] GetQuestionAnswers(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetQuestionAnswers", ReplyAction="http://tempuri.org/IStudentTestService/GetQuestionAnswersResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.AnswerViewModel[]> GetQuestionAnswersAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetResults", ReplyAction="http://tempuri.org/IStudentTestService/GetResultsResponse")]
        AdminWPFClient.ServiceReference.ResultViewModel[] GetResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetResults", ReplyAction="http://tempuri.org/IStudentTestService/GetResultsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.ResultViewModel[]> GetResultsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetQuestions", ReplyAction="http://tempuri.org/IStudentTestService/GetQuestionsResponse")]
        AdminWPFClient.ServiceReference.QuestionViewModel[] GetQuestions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetQuestions", ReplyAction="http://tempuri.org/IStudentTestService/GetQuestionsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.QuestionViewModel[]> GetQuestionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTestGroups", ReplyAction="http://tempuri.org/IStudentTestService/GetTestGroupsResponse")]
        AdminWPFClient.ServiceReference.GroupViewModel[] GetTestGroups(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetTestGroups", ReplyAction="http://tempuri.org/IStudentTestService/GetTestGroupsResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.GroupViewModel[]> GetTestGroupsAsync(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetResultAnswers", ReplyAction="http://tempuri.org/IStudentTestService/GetResultAnswersResponse")]
        AdminWPFClient.ServiceReference.ResultAnswerViewModel[] GetResultAnswers(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/GetResultAnswers", ReplyAction="http://tempuri.org/IStudentTestService/GetResultAnswersResponse")]
        System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.ResultAnswerViewModel[]> GetResultAnswersAsync(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/IsAcceess", ReplyAction="http://tempuri.org/IStudentTestService/IsAcceessResponse")]
        bool IsAcceess(int groupId, int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/IsAcceess", ReplyAction="http://tempuri.org/IStudentTestService/IsAcceessResponse")]
        System.Threading.Tasks.Task<bool> IsAcceessAsync(int groupId, int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateStudent", ReplyAction="http://tempuri.org/IStudentTestService/CreateStudentResponse")]
        void CreateStudent(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateStudent", ReplyAction="http://tempuri.org/IStudentTestService/CreateStudentResponse")]
        System.Threading.Tasks.Task CreateStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateGroup", ReplyAction="http://tempuri.org/IStudentTestService/CreateGroupResponse")]
        void CreateGroup(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateGroup", ReplyAction="http://tempuri.org/IStudentTestService/CreateGroupResponse")]
        System.Threading.Tasks.Task CreateGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateTest", ReplyAction="http://tempuri.org/IStudentTestService/CreateTestResponse")]
        void CreateTest(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateTest", ReplyAction="http://tempuri.org/IStudentTestService/CreateTestResponse")]
        System.Threading.Tasks.Task CreateTestAsync(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateQuestion", ReplyAction="http://tempuri.org/IStudentTestService/CreateQuestionResponse")]
        void CreateQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateQuestion", ReplyAction="http://tempuri.org/IStudentTestService/CreateQuestionResponse")]
        System.Threading.Tasks.Task CreateQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateAnswer", ReplyAction="http://tempuri.org/IStudentTestService/CreateAnswerResponse")]
        void CreateAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateAnswer", ReplyAction="http://tempuri.org/IStudentTestService/CreateAnswerResponse")]
        System.Threading.Tasks.Task CreateAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateAccess", ReplyAction="http://tempuri.org/IStudentTestService/CreateAccessResponse")]
        void CreateAccess(int groupId, int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/CreateAccess", ReplyAction="http://tempuri.org/IStudentTestService/CreateAccessResponse")]
        System.Threading.Tasks.Task CreateAccessAsync(int groupId, int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentTestService/UpdateStudentResponse")]
        void UpdateStudent(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentTestService/UpdateStudentResponse")]
        System.Threading.Tasks.Task UpdateStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateGroup", ReplyAction="http://tempuri.org/IStudentTestService/UpdateGroupResponse")]
        void UpdateGroup(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateGroup", ReplyAction="http://tempuri.org/IStudentTestService/UpdateGroupResponse")]
        System.Threading.Tasks.Task UpdateGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateTest", ReplyAction="http://tempuri.org/IStudentTestService/UpdateTestResponse")]
        void UpdateTest(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateTest", ReplyAction="http://tempuri.org/IStudentTestService/UpdateTestResponse")]
        System.Threading.Tasks.Task UpdateTestAsync(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateQuestion", ReplyAction="http://tempuri.org/IStudentTestService/UpdateQuestionResponse")]
        void UpdateQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateQuestion", ReplyAction="http://tempuri.org/IStudentTestService/UpdateQuestionResponse")]
        System.Threading.Tasks.Task UpdateQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateAnswer", ReplyAction="http://tempuri.org/IStudentTestService/UpdateAnswerResponse")]
        void UpdateAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/UpdateAnswer", ReplyAction="http://tempuri.org/IStudentTestService/UpdateAnswerResponse")]
        System.Threading.Tasks.Task UpdateAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentTestService/DeleteStudentResponse")]
        void DeleteStudent(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentTestService/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteGroup", ReplyAction="http://tempuri.org/IStudentTestService/DeleteGroupResponse")]
        void DeleteGroup(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteGroup", ReplyAction="http://tempuri.org/IStudentTestService/DeleteGroupResponse")]
        System.Threading.Tasks.Task DeleteGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteTest", ReplyAction="http://tempuri.org/IStudentTestService/DeleteTestResponse")]
        void DeleteTest(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteTest", ReplyAction="http://tempuri.org/IStudentTestService/DeleteTestResponse")]
        System.Threading.Tasks.Task DeleteTestAsync(AdminWPFClient.ServiceReference.TestViewModel test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteQuestion", ReplyAction="http://tempuri.org/IStudentTestService/DeleteQuestionResponse")]
        void DeleteQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteQuestion", ReplyAction="http://tempuri.org/IStudentTestService/DeleteQuestionResponse")]
        System.Threading.Tasks.Task DeleteQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteAnswer", ReplyAction="http://tempuri.org/IStudentTestService/DeleteAnswerResponse")]
        void DeleteAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteAnswer", ReplyAction="http://tempuri.org/IStudentTestService/DeleteAnswerResponse")]
        System.Threading.Tasks.Task DeleteAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteAccess", ReplyAction="http://tempuri.org/IStudentTestService/DeleteAccessResponse")]
        void DeleteAccess(int groupId, int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentTestService/DeleteAccess", ReplyAction="http://tempuri.org/IStudentTestService/DeleteAccessResponse")]
        System.Threading.Tasks.Task DeleteAccessAsync(int groupId, int testId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentTestServiceChannel : AdminWPFClient.ServiceReference.IStudentTestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentTestServiceClient : System.ServiceModel.ClientBase<AdminWPFClient.ServiceReference.IStudentTestService>, AdminWPFClient.ServiceReference.IStudentTestService {
        
        public StudentTestServiceClient() {
        }
        
        public StudentTestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdminWPFClient.ServiceReference.StudentViewModel[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.StudentViewModel[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public AdminWPFClient.ServiceReference.GroupViewModel[] GetGroups() {
            return base.Channel.GetGroups();
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.GroupViewModel[]> GetGroupsAsync() {
            return base.Channel.GetGroupsAsync();
        }
        
        public AdminWPFClient.ServiceReference.TestViewModel[] GetTests() {
            return base.Channel.GetTests();
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.TestViewModel[]> GetTestsAsync() {
            return base.Channel.GetTestsAsync();
        }
        
        public AdminWPFClient.ServiceReference.TestViewModel[] GetStudentTests(int studentId) {
            return base.Channel.GetStudentTests(studentId);
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.TestViewModel[]> GetStudentTestsAsync(int studentId) {
            return base.Channel.GetStudentTestsAsync(studentId);
        }
        
        public AdminWPFClient.ServiceReference.QuestionViewModel[] GetTestQuestions(int testId) {
            return base.Channel.GetTestQuestions(testId);
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.QuestionViewModel[]> GetTestQuestionsAsync(int testId) {
            return base.Channel.GetTestQuestionsAsync(testId);
        }
        
        public AdminWPFClient.ServiceReference.AnswerViewModel[] GetQuestionAnswers(int questionId) {
            return base.Channel.GetQuestionAnswers(questionId);
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.AnswerViewModel[]> GetQuestionAnswersAsync(int questionId) {
            return base.Channel.GetQuestionAnswersAsync(questionId);
        }
        
        public AdminWPFClient.ServiceReference.ResultViewModel[] GetResults() {
            return base.Channel.GetResults();
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.ResultViewModel[]> GetResultsAsync() {
            return base.Channel.GetResultsAsync();
        }
        
        public AdminWPFClient.ServiceReference.QuestionViewModel[] GetQuestions() {
            return base.Channel.GetQuestions();
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.QuestionViewModel[]> GetQuestionsAsync() {
            return base.Channel.GetQuestionsAsync();
        }
        
        public AdminWPFClient.ServiceReference.GroupViewModel[] GetTestGroups(int testId) {
            return base.Channel.GetTestGroups(testId);
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.GroupViewModel[]> GetTestGroupsAsync(int testId) {
            return base.Channel.GetTestGroupsAsync(testId);
        }
        
        public AdminWPFClient.ServiceReference.ResultAnswerViewModel[] GetResultAnswers(int resultId) {
            return base.Channel.GetResultAnswers(resultId);
        }
        
        public System.Threading.Tasks.Task<AdminWPFClient.ServiceReference.ResultAnswerViewModel[]> GetResultAnswersAsync(int resultId) {
            return base.Channel.GetResultAnswersAsync(resultId);
        }
        
        public bool IsAcceess(int groupId, int testId) {
            return base.Channel.IsAcceess(groupId, testId);
        }
        
        public System.Threading.Tasks.Task<bool> IsAcceessAsync(int groupId, int testId) {
            return base.Channel.IsAcceessAsync(groupId, testId);
        }
        
        public void CreateStudent(AdminWPFClient.ServiceReference.StudentViewModel student) {
            base.Channel.CreateStudent(student);
        }
        
        public System.Threading.Tasks.Task CreateStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student) {
            return base.Channel.CreateStudentAsync(student);
        }
        
        public void CreateGroup(AdminWPFClient.ServiceReference.GroupViewModel group) {
            base.Channel.CreateGroup(group);
        }
        
        public System.Threading.Tasks.Task CreateGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group) {
            return base.Channel.CreateGroupAsync(group);
        }
        
        public void CreateTest(AdminWPFClient.ServiceReference.TestViewModel test) {
            base.Channel.CreateTest(test);
        }
        
        public System.Threading.Tasks.Task CreateTestAsync(AdminWPFClient.ServiceReference.TestViewModel test) {
            return base.Channel.CreateTestAsync(test);
        }
        
        public void CreateQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            base.Channel.CreateQuestion(question);
        }
        
        public System.Threading.Tasks.Task CreateQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            return base.Channel.CreateQuestionAsync(question);
        }
        
        public void CreateAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            base.Channel.CreateAnswer(answer);
        }
        
        public System.Threading.Tasks.Task CreateAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            return base.Channel.CreateAnswerAsync(answer);
        }
        
        public void CreateAccess(int groupId, int testId) {
            base.Channel.CreateAccess(groupId, testId);
        }
        
        public System.Threading.Tasks.Task CreateAccessAsync(int groupId, int testId) {
            return base.Channel.CreateAccessAsync(groupId, testId);
        }
        
        public void UpdateStudent(AdminWPFClient.ServiceReference.StudentViewModel student) {
            base.Channel.UpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task UpdateStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student) {
            return base.Channel.UpdateStudentAsync(student);
        }
        
        public void UpdateGroup(AdminWPFClient.ServiceReference.GroupViewModel group) {
            base.Channel.UpdateGroup(group);
        }
        
        public System.Threading.Tasks.Task UpdateGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group) {
            return base.Channel.UpdateGroupAsync(group);
        }
        
        public void UpdateTest(AdminWPFClient.ServiceReference.TestViewModel test) {
            base.Channel.UpdateTest(test);
        }
        
        public System.Threading.Tasks.Task UpdateTestAsync(AdminWPFClient.ServiceReference.TestViewModel test) {
            return base.Channel.UpdateTestAsync(test);
        }
        
        public void UpdateQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            base.Channel.UpdateQuestion(question);
        }
        
        public System.Threading.Tasks.Task UpdateQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            return base.Channel.UpdateQuestionAsync(question);
        }
        
        public void UpdateAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            base.Channel.UpdateAnswer(answer);
        }
        
        public System.Threading.Tasks.Task UpdateAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            return base.Channel.UpdateAnswerAsync(answer);
        }
        
        public void DeleteStudent(AdminWPFClient.ServiceReference.StudentViewModel student) {
            base.Channel.DeleteStudent(student);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(AdminWPFClient.ServiceReference.StudentViewModel student) {
            return base.Channel.DeleteStudentAsync(student);
        }
        
        public void DeleteGroup(AdminWPFClient.ServiceReference.GroupViewModel group) {
            base.Channel.DeleteGroup(group);
        }
        
        public System.Threading.Tasks.Task DeleteGroupAsync(AdminWPFClient.ServiceReference.GroupViewModel group) {
            return base.Channel.DeleteGroupAsync(group);
        }
        
        public void DeleteTest(AdminWPFClient.ServiceReference.TestViewModel test) {
            base.Channel.DeleteTest(test);
        }
        
        public System.Threading.Tasks.Task DeleteTestAsync(AdminWPFClient.ServiceReference.TestViewModel test) {
            return base.Channel.DeleteTestAsync(test);
        }
        
        public void DeleteQuestion(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            base.Channel.DeleteQuestion(question);
        }
        
        public System.Threading.Tasks.Task DeleteQuestionAsync(AdminWPFClient.ServiceReference.QuestionViewModel question) {
            return base.Channel.DeleteQuestionAsync(question);
        }
        
        public void DeleteAnswer(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            base.Channel.DeleteAnswer(answer);
        }
        
        public System.Threading.Tasks.Task DeleteAnswerAsync(AdminWPFClient.ServiceReference.AnswerViewModel answer) {
            return base.Channel.DeleteAnswerAsync(answer);
        }
        
        public void DeleteAccess(int groupId, int testId) {
            base.Channel.DeleteAccess(groupId, testId);
        }
        
        public System.Threading.Tasks.Task DeleteAccessAsync(int groupId, int testId) {
            return base.Channel.DeleteAccessAsync(groupId, testId);
        }
    }
}
